language: java
jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2'

install: ./mvnw clean install -Dgpg.skip

jobs:
  include:
    - stage: Test
      script: echo 'Build and Test ' $TRAVIS_BRANCH

    - stage: deploy
      sudo: false
      services: []
      install: skip
      script: skip
      before_deploy:
        - openssl aes-256-cbc  -in release/codesigning.asc.enc -out release/codesigning.asc -d -k $CODESIGNING
        - gpg --fast-import release/codesigning.asc
        - rm release/codesigning.asc
      deploy:
        - provider: script
          skip_cleanup: true
          script: bash ./mvnw deploy -Drevision=$TRAVIS_TAG -Dgpg_key=$GPG_KEY -Dgpg.passphrase=$GPG_PASSPHRASE
          on:
            tags: true
            branch: master
      after_deploy: echo 'Finish to deploy'