language: java
jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2'

before_install: gpg --fast-import release/keys

install: ./mvnw install -Dgpg_key=$GPGKEY -Dgpg.passphrase=$GPG_PASSPHRASE
#script: ./mvnw verify -Drevision=$TRAVIS_TAG -Dgpg.skip
#   on:
#            tags: true
#            branch: master

jobs:
  include:
    - stage: deploy
      sudo: false
      services: []
      install: skip
      script: skip
      deploy:
        provider: script
        script: release/verify.sh
        on:
          tags: true
          branch: master