language: java
jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2'

# import GPG key into environment
before_install:
  - gpg --fast-import release/keys

install: ./mvnw install -Dgpg_key=$GPG_KEY -Dgpg.passphrase=$GPG_PASSPHRASE

jobs:
  include:
    - stage: install
      script: echo " Build and Test " $TRAVIS_BRANCH
    - stage: deploy
      sudo: false
      services: []
      install: skip
      script: skip
      deploy:
        provider: script
        script: bash ./mvnw verify -Drevision=$TRAVIS_TAG -Dgpg_key=$GPG_KEY -Dgpg.passphrase=$GPG_PASSPHRASE
        on:
          tags: true
          branch: master
      after_deploy: echo "Finush deploy release " $TRAVIS_TAG    

