language: java
jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2'

install: ./mvnw clean install -Dgpg.skip

jobs:
  include:
    - stage: Test
      script: echo 'Build and Test ' $TRAVIS_BRANCH
    - stage: Deploy
      sudo: false
      services: []
      install: skip
      script: skip
      before_deploy: echo 'BEFORE DEPLOY ' $TRAVIS_TAG
      deploy:
        provider: script
        script: release/verify.sh
#        script: bash ./mvnw verify -Drevision=$TRAVIS_TAG -Dgpg_key=$GPG_KEY -Dgpg.passphrase=$GPG_PASSPHRASE
        on:
          tags: true
          branch: master
      after_deploy: echo 'Finish deploy release ' $TRAVIS_TAG

