language: java
jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2'

install: ./mvnw clean install -Dgpg.skip

jobs:
  include:
    - stage: Test
      script: echo 'Build and Test ' $TRAVIS_BRANCH
    - stage: Deploy
      sudo: false
      services: []
      install: skip
      script: skip
      before_deploy:
        - openssl aes-256-cbc  -in release/codesigning.asc.enc -out release/codesigning.asc -d -k $CODESIGNING
        - gpg --fast-import release/codesigning.asc
        - ./mvnw versions:set -DnewVersion=$TRAVIS_TAG
      deploy:
        provider: script
#        script: release/verify.sh
        script: bash ./mvnw verify -Drevision=$TRAVIS_TAG -Dgpg_key=$GPG_KEY -Dgpg.passphrase=$GPG_PASSPHRASE
#          - bash ./mvnw versions:set -DnewVersion=$TRAVIS_TAG
#          - bash ./mvnw verify -Dgpg_key=$GPG_KEY -Dgpg.passphrase=$GPG_PASSPHRASE
#          - bash ./mvnw verify -Drevision=$TRAVIS_TAG -Dgpg_key=$GPG_KEY -Dgpg.passphrase=$GPG_PASSPHRASE
#          - bash echo 'Finish to deploy' $TRAVIS_TAG
        on:
          tags: true
          branch: master
      after_deploy: rm release/codesigning.asc

