language: java
jdk:
- oraclejdk8
#install: ./mvnw install -Dgpg.skip
#install:
#  ./mvnw -Drevision==$TRAVIS_TAG verify -Dgpg.skip
#-Dgpg.passphrase=Asia2307
before_deploy: "echo $TRAVIS_TAG"
 on:
  tags: true
  branch:master
  
# deploy:
  # provider: script
   # script: echo $TRAVIS_TAG
#      - ./mvnw -Drevision==$TRAVIS_TAG verify -Dgpg.skip
   # on:
    #  tags: true
     # branch: master
