language: java
jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2'

# import GPG key into environment
before_install:
  - gpg --fast-import release/keys

install: ./mvnw install -Dgpg_key=$GPG_KEY -Dgpg.passphrase=$GPG_PASSPHRASE

deploy: ./mvnw verify -Drevision=$TRAVIS_TAG -Dgpg.passphrase=$GPG_PASSPHRASE

jobs:
  include:
    - stage: deploy
      sudo: false
      services: []
#      install: skip
      script: skip
      deploy:
#        provider: script
#        script: release/verify.sh
        on:
          tags: true
          branch: master