language: java
jdk: oraclejdk8

cache:
  directories:
    - '$HOME/.m2'

install: ./mvnw clean install -Dgpg.skip

jobs:
  include:
    - stage: Test
      script: echo 'Build and Test ' $TRAVIS_BRANCH
    - stage: Deploy
      sudo: false
      services: []
      install: skip
      script: skip
      before_deploy:
        - openssl aes-256-cbc  -in release/codesigning.asc.enc -out release/codesigning.asc -d -k $CODESIGNING
        - gpg --fast-import release/codesigning.asc
        - rm release/codesigning.asc
        - ./mvnw versions:set -DnewVersion=$TRAVIS_TAG
      deploy:
        # deploy to central repository
#        - provider: script
#          skip_cleanup: true
#          script: bash ./mvnw verify -Dgpg_key=$GPG_KEY -Dgpg.passphrase=$GPG_PASSPHRASE
#          on:
#            tags: true
#            branch: master
        # deploy to github new version
        - provider: pages
          skip_cleanup: true
          target-branch: master
          github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
          keep-history: true
          on:
            tags: true
            branch: master

      after_deploy: echo '!!!!!!!!!!!!!'